
services:
  web:
    build: .
    image: ludwig91/livros_narrados_fastgpu:v7
    command: ["web"]
    restart: no
    ports:
      - "8088:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, video]

  worker:
    image: ludwig91/livros_narrados_fastgpu:v7
    command: ["worker"]
    restart: no
    volumes:
      - ./data:/app/data
    depends_on:
      redis:
        condition: service_healthy
      web:
        condition: service_started
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - NVIDIA_DRIVER_CAPABILITIES=all
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu, utility, video]

  redis:
    image: redis:alpine
    restart: no
    ports:
      - "6388:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis_data: