version: '3.8'

services:
  web:
    image: ludwig91/livros_narrados_v2:latest
    command: ["web"]
    ports:
      - "8088:8000"
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    image: ludwig91/livros_narrados_v2:latest
    command: ["worker"]
    volumes:
      - ./data:/app/data
    depends_on:
      - redis
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
